# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish Packages
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # Fetch sources
      - name: Fetch Sources
        uses: actions/checkout@v3

      # Validate wrapper
      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.4

      # Read properties
      - name: Read project properties
        id: project_properties
        uses: christian-draeger/read-properties@1.1.0
        with:
          path: './gradle.properties'
          properties: 'gradle-version java-version'

      # Setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ steps.project_properties.outputs.java-version }}
          distribution: temurin

      # Publish to GitHub Packages
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: ${{ steps.project_properties.outputs.gradle-version }}
          arguments: publish
        env:
          TAG_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}